import { readdirSync, statSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";

const TEMPLATES_DIR = join(import.meta.dirname, "..", "src", "templates");
const OUTPUT_FILE = join(import.meta.dirname, "..", "src", "templates", "bundle.ts");

function walk(dir: string, result: Record<string, string> = {}): Record<string, string> {
  const entries = readdirSync(dir);
  for (const entry of entries) {
    const path = join(dir, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      walk(path, result);
    } else {
      const rel = relative(TEMPLATES_DIR, path).replace(/\\/g, "/");
      const content = readFileSync(path, "utf-8");
      result[rel] = content;
    }
  }
  return result;
}

const bundle = walk(TEMPLATES_DIR);

const lines = [
  "// AUTO-GENERATED by scripts/bundle-templates.ts",
  "// Do not edit manually — run 'bun run scripts/bundle-templates.ts' to regenerate",
  "",
  "export const templateBundle: Record<string, string> = {",
];

for (const [path, content] of Object.entries(bundle)) {
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  lines.push(`  "${path}": \`${escaped}\`,`);
}

lines.push("};");
lines.push("");
lines.push("export function getTemplatePaths(): string[] {");
lines.push("  return Object.keys(templateBundle);");
lines.push("}");
lines.push("");
lines.push("export function getTemplateContent(path: string): string | null {");
lines.push("  return templateBundle[path] ?? null;");
lines.push("}");

import { writeFileSync } from "node:fs";
writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
console.log(`Bundled ${Object.keys(bundle).length} templates into ${OUTPUT_FILE}`);