import { readdirSync, statSync, readFileSync } from "node:fs";
import { join, relative } from "node:path";

const MODULES_DIR = join(import.meta.dirname, "..", "src", "modules", "built-in");
const OUTPUT_FILE = join(import.meta.dirname, "..", "src", "modules", "bundle.ts");

function walk(dir: string, result: Record<string, string> = {}): Record<string, string> {
  const entries = readdirSync(dir);
  for (const entry of entries) {
    const path = join(dir, entry);
    const stat = statSync(path);
    if (stat.isDirectory()) {
      walk(path, result);
    } else {
      const rel = relative(MODULES_DIR, path).replace(/\\/g, "/");
      const content = readFileSync(path, "utf-8");
      result[rel] = content;
    }
  }
  return result;
}

const bundle = walk(MODULES_DIR);

const lines = [
  "// AUTO-GENERATED by scripts/bundle-modules.ts",
  "// Do not edit manually — run 'bun run scripts/bundle-modules.ts' to regenerate",
  "",
  "export const moduleBundle: Record<string, string> = {",
];

for (const [path, content] of Object.entries(bundle)) {
  const escaped = content
    .replace(/\\/g, "\\\\")
    .replace(/`/g, "\\`")
    .replace(/\$/g, "\\$")
    .replace(/\n/g, "\\n")
    .replace(/\r/g, "\\r")
    .replace(/\t/g, "\\t");
  lines.push(`  "${path}": \`${escaped}\`,`);
}

lines.push("};");
lines.push("");
lines.push("export function getModulePaths(): string[] {");
lines.push("  return Object.keys(moduleBundle);");
lines.push("}");
lines.push("");
lines.push("export function getModuleContent(path: string): string | null {");
lines.push("  return moduleBundle[path] ?? null;");
lines.push("}");
lines.push("");
lines.push("export function listBuiltInModules(): string[] {");
lines.push("  const dirs = new Set<string>();");
lines.push("  for (const path of Object.keys(moduleBundle)) {");
lines.push("    const top = path.split('/')[0];");
lines.push("    dirs.add(top);");
lines.push("  }");
lines.push("  return Array.from(dirs);");
lines.push("}");

import { writeFileSync } from "node:fs";
writeFileSync(OUTPUT_FILE, lines.join("\n"), "utf-8");
console.log(`Bundled ${Object.keys(bundle).length} module files into ${OUTPUT_FILE}`);